package com.paywallet.userservice.user.enums;

public enum BorrowerEventEnum {

    UMS_CUST_CREATE_INPROG("UMS-CUST-CREATE-INPROG"),
    UMS_GET_REQ_DETAIL_INPROG("UMS-GET-REQ-DETAIL-INPROG"),
    UMS_GET_REQ_DETAIL_SUCC("UMS-GET-REQ-DETAIL-SUCC"),
    UMS_GET_REQ_DETAIL_FAIL("UMS-GET-REQ-DETAIL-FAIL"),
    UMS_CUST_CREATE_FINERACT_VIRTUAL_ACCT_INPROG("UMS-CUST-CREATE-FINERACT-VIRTUAL-ACCT-INPROG"),
    UMS_CUST_CREATE_FINERACT_VIRTUAL_ACCT_SUCC("UMS-CUST-CREATE-FINERACT-VIRTUAL-ACCT-SUCC"),
    UMS_CUST_CREATE_FINERACT_VIRTUAL_ACCT_FAIL("UMS-CUST-CREATE-FINERACT-VIRTUAL-ACCT-FAIL"),

    UMS_UPD_REQ_DETAIL_INPROG("UMS-CUST-UPT-REQ-DETAIL-INPROGRESS"),
    UMS_UPD_REQ_DETAIL_SUCC("UMS-CUST-UPT-REQ-DETAIL-SUCC"),
    UMS_UPD_REQ_DETAIL_FAIL("UMS-CUST-UPT-REQ-DETAIL-FAIL"),

    UMS_CUST_CREATE_SUCC("UMS-CUST-CREATE-SUCC"),
    UMS_CUST_CREATE_FAIL("UMS-CUST-CREATE-FAIL"),

    UMS_CUST_GET_BY_MOBILE_INPROG("UMS-CUST-GET-BY-MOBILE-INPROG"),
    UMS_CUST_GET_BY_MOBILE_SUCC("UMS-CUST-GET-BY-MOBILE-SUCC"),
    UMS_CUST_GET_BY_MOBILE_FAIL("UMS-CUST-GET-BY-MOBILE-FAIL"),
    UMS_CUST_GET_INPROG("UMS-CUST-GET-INPROG"),
    UMS_CUST_GET_SUCC("UMS-CUST-GET-SUCC"),
    UMS_CUST_GET_FAIL("UMS-CUST-GET-FAIL"),

    UMS_CUST_ACCT_VAL_INPROG("UMS-CUST-ACCT-VAL-INPROG"),
    UMS_CUST_LYON_ACCT_VAL_INPROG("UMS-CUST-LYON-ACCT-VAL-INPROG"),
    UMS_CUST_LYON_ACCT_VAL_SUCC("UMS-CUST-LYON-ACCT-VAL-SUCC"),
    UMS_CUST_LYON_ACCT_VAL_FAIL("UMS-CUST-LYON-ACCT-VAL-FAIL"),
    UMS_CUST_ACCT_VAL_SUCC("UMS-CUST-ACCT-VAL-SUCC"),
    UMS_CUST_ACCT_VAL_FAIL("UMS-CUST-ACCT-VAL-FAIL"),

    UMS_CUST_UPD_INPROG("UMS-CUST-UPD-INPROG"),
    UMS_CUST_UPD_SUCC("UMS-CUST-UPD-SUCC"),
    UMS_CUST_UPD_FAIL("UMS-CUST-UPD-FAIL"),

    UMS_CUST_ACCT_GET_BY_MOBILE_INPROG("UMS-CUST-ACCT-GET-BY-MOBILE-INPROG"),
    UMS_CUST_ACCT_GET_BY_MOBILE_SUCC("UMS-CUST-ACCT-GET-BY-MOBILE-SUCC"),
    UMS_CUST_ACCT_GET_BY_MOBILE_FAIL("UMS-CUST-ACCT-GET-BY-MOBILE-FAIL"),

    ;
    private String message;
    BorrowerEventEnum(){}
    BorrowerEventEnum(String message) {
        this.message = message;
    }

    public String getMessage(){
        return this.message;
    }

}
