package com.paywallet.userservice.user.enums;

public enum BorrowerEventEnum {

    UMS_CUST_CREATE_INPROG("UMS-CUST-CREATE-INPROG"),
    UMS_GET_REQ_DETAIL_INPROG("UMS-GET-REQ-DETAIL-INPROG"),
    UMS_GET_REQ_DETAIL_SUCC("UMS-GET-REQ-DETAIL-SUCC"),
    UMS_GET_REQ_DETAIL_FAIL("UMS-GET-REQ-DETAIL-FAIL"),
    UMS_CUST_CREATE_FINERACT_VIRTUAL_ACCT_INPROG("UMS-CUST-CREATE-FINERACT-VIRTUAL-ACCT-INPROG"),
    UMS_CUST_CREATE_FINERACT_VIRTUAL_ACCT_SUCC("UMS-CUST-CREATE-FINERACT-VIRTUAL-ACCT-SUCC"),
    UMS_CUST_CREATE_FINERACT_VIRTUAL_ACCT_FAIL("UMS-CUST-CREATE-FINERACT-VIRTUAL-ACCT-FAIL"),

    UMS_UPD_REQ_DETAIL_INPROG("UMS-CUST-UPT-REQ-DETAIL-INPROGRESS"),
    UMS_UPD_REQ_DETAIL_SUCC("UMS-CUST-UPT-REQ-DETAIL-SUCC"),
    UMS_UPD_REQ_DETAIL_FAIL("UMS-CUST-UPT-REQ-DETAIL-FAIL"),

    UMS_CUST_CREATE_SUCC("UMS-CUST-CREATE-SUCC"),
    UMS_CUST_CREATE_FAIL("UMS-CUST-CREATE-FAIL"),

    UMS_CUST_GET_BY_MOBILE_INPROG("UMS-CUST-GET-BY-MOBILE-INPROG"),
    UMS_CUST_GET_BY_MOBILE_SUCC("UMS-CUST-GET-BY-MOBILE-SUCC"),
    UMS_CUST_GET_BY_MOBILE_FAIL("UMS-CUST-GET-BY-MOBILE-FAIL"),
    UMS_CUST_GET_INPROG("UMS-CUST-GET-INPROG"),
    UMS_CUST_GET_SUCC("UMS-CUST-GET-SUCC"),
    UMS_CUST_GET_FAIL("UMS-CUST-GET-FAIL"),

    UMS_CUST_ACCT_VAL_INPROG("UMS-CUST-ACCT-VAL-INPROG"),
    UMS_CUST_LYON_ACCT_VAL_INPROG("UMS-CUST-LYON-ACCT-VAL-INPROG"),
    UMS_CUST_LYON_ACCT_VAL_SUCC("UMS-CUST-LYON-ACCT-VAL-SUCC"),
    UMS_CUST_LYON_ACCT_VAL_FAIL("UMS-CUST-LYON-ACCT-VAL-FAIL"),
    UMS_CUST_ACCT_VAL_SUCC("UMS-CUST-ACCT-VAL-SUCC"),
    UMS_CUST_ACCT_VAL_FAIL("UMS-CUST-ACCT-VAL-FAIL"),

    UMS_CUST_UPD_INPROG("UMS-CUST-UPD-INPROG"),
    UMS_CUST_UPD_SUCC("UMS-CUST-UPD-SUCC"),
    UMS_CUST_UPD_FAIL("UMS-CUST-UPD-FAIL"),

    UMS_CUST_ACCT_GET_BY_MOBILE_INPROG("UMS-CUST-ACCT-GET-BY-MOBILE-INPROG"),
    UMS_CUST_ACCT_GET_BY_MOBILE_SUCC("UMS-CUST-ACCT-GET-BY-MOBILE-SUCC"),
    UMS_CUST_ACCT_GET_BY_MOBILE_FAIL("UMS-CUST-ACCT-GET-BY-MOBILE-FAIL"),

    //Event logging changes for wrapper Api's
    UMS_INITIATE_DEPOSIT_ALLOCATION_INPROG("UMS-INITIATE-DEPOSIT-ALLOCATION-INPROG"),
    UMS_INITIATE_DEPOSIT_ALLOCATION_SUCC("UMS-INITIATE-DEPOSIT-ALLOCATION-SUCC"),
    UMS_INITIATE_DEPOSIT_ALLOCATION_FAIL("UMS-INITIATE-DEPOSIT-ALLOCATION-FAIL"),

    UMS_INITIATE_EMPLOYMENT_VERIFICATION_INPROG("UMS-INITIATE-EMPLOYMENT-VERIFICATION-INPROG"),
    UMS_INITIATE_EMPLOYMENT_VERIFICATION_SUCC("UMS-INITIATE-EMPLOYMENT-VERIFICATION-SUCC"),
    UMS_INITIATE_EMPLOYMENT_VERIFICATION_FAIL("UMS-INITIATE-EMPLOYMENT-VERIFICATION-FAIL"),

    UMS_INITIATE_INCOME_VERIFICATION_INPROG("UMS-INITIATE-INCOME-VERIFICATION-INPROG"),
    UMS_INITIATE_INCOME_VERIFICATION_SUCC("UMS-INITIATE-INCOME-VERIFICATION-SUCC"),
    UMS_INITIATE_INCOME_VERIFICATION_FAIL("UMS-INITIATE-INCOME-VERIFICATION-FAIL"),

    UMS_INITIATE_IDENTITY_VERIFICATION_INPROG("UMS-INITIATE-IDENTITY-VERIFICATION-INPROG"),
    UMS_INITIATE_IDENTITY_VERIFICATION_SUCC("UMS-INITIATE-IDENTITY-VERIFICATION-SUCC"),
    UMS_INITIATE_IDENTITY_VERIFICATION_FAIL("UMS-INITIATE-IDENTITY-VERIFICATION-FAIL"),


    UMS_EMPLOYMENT_VERIFICATION_RETRY_INPROG("UMS-EMPLOYMENT-VERIFICATION-RETRY-INPROG"),
    UMS_EMPLOYMENT_VERIFICATION_RETRY_SUCC("UMS-EMPLOYMENT-VERIFICATION-RETRY-SUCC"),
    UMS_EMPLOYMENT_VERIFICATION_RETRY_FAIL("UMS-EMPLOYMENT-VERIFICATION-RETRY-FAIL"),


    UMS_IDENTITY_VERIFICATION_RETRY_INPROG("UMS-IDENTITY-VERIFICATION-RETRY-INPROG"),
    UMS_IDENTITY_VERIFICATION_RETRY_SUCC("UMS-IDENTITY-VERIFICATION-RETRY-SUCC"),
    UMS_IDENTITY_VERIFICATION_RETRY_FAIL("UMS-IDENTITY-VERIFICATION-RETRY-FAIL"),


    UMS_INCOME_VERIFICATION_RETRY_INPROG("UMS-INCOME-VERIFICATION-RETRY-INPROG"),
    UMS_INCOME_VERIFICATION_RETRY_SUCC("UMS-INCOME-VERIFICATION-RETRY-SUCC"),
    UMS_INCOME_VERIFICATION_RETRY_FAIL("UMS-INCOME-VERIFICATION-RETRY-FAIL"),
    ;
    private String message;
    BorrowerEventEnum(){}
    BorrowerEventEnum(String message) {
        this.message = message;
    }

    public String getMessage(){
        return this.message;
    }

}
