package com.paywallet.userservice.user.enums;

public enum FlowTypeEnum {
	
	GENERAL,
	EMPLOYMENT_VERIFICATION,
	IDENTITY_VERIFICATION,
	INCOME_VERIFICATION,
	ACCOUNT_VALIDATION,
	DEPOSIT_ALLOCATION
}
